### ISSUE TITLE
No member named ‘emplace_back’

### ISSUE THREAD

**Issue by ridhij93** [nidhugg/nidhugg#63]
Getting the following error while running make:

RFSCTraceBuilder.cpp:947:15: error: ‘RFSCTraceBuilder::UnfoldingNodeChildren {aka class llvm::SmallVector<std::weak_ptr<RFSCTraceBuilder::UnfoldingNode>, 1u>}’ has no member named ‘emplace_back’; did you mean ‘push_back’?
   parent_list.emplace_back(c);
               ^~~~~~~~~~~~
Can anyone suggest what could be the possible reason?
[Already using gcc-6.5]

**Comment by kostis** [comment]
You need to provide us with some more info for this.  For example, what is your LLVM version and OS you are running on?  Have you installed all dependencies specified in the README?

@margnus1 : I just noticed that the [README in this line](https://github.com/nidhugg/nidhugg/blob/master/README#L127) erroneously still specifies a (quite old) C++ compiler that supports C++11.  This should be changed to an appropriate version of a compiler that supports C++14 instead.

**Comment by kostis** [comment]
A Google search reveals that this problem exists either when your C++ compiler does not properly support C++11 or when you do not have the appropriate version of boost available.  It's probably one of these two that's the culprit.

**Comment by ridhij93** [comment]
I replaced emplace_back with push_back and it compiled without errors. [Hoping this won't affect the tool]

Other details that remain unchanged:
OS: Ubuntu 14.04
Kernel: 3.13.0-170-generic
g++: 6.5.0 
clang: 3.8
Python 3.4.3

**Comment by kostis** [comment]
I think the problem is that your Ubuntu version is, in computer-time, ancient (it's based on something released on April 2014 whose standard support ended in April this year).  There are two LTS releases  (16.04 and 18.04) after that and, independently of Nidhugg, you will be better off upgrading to them.

But the change you did in the code is most likely alright and you should not have a problem with it.
Thanks for your interest in Nidhugg -- we will appreciate feedback.

**Comment by margnus1** [comment]
It's strange that you're getting this error. That function is certainly available in llvm 3.8. Could it be that you are compiling against llvm 3.6?

In any case, I will make the `emplace_back -> push_back` change, since it costs us nothing; but if we could figure out why you got this error we could either tell you what part of your system is too old for nidhugg, or include it in our testing so that this does not happen again.
