### ISSUE TITLE
__VERIFIER_assume behavior?

### ISSUE THREAD

**Issue by mchalupa** [nidhugg/nidhugg#7]
Hi,

I saw in the benchmarks (https://github.com/nidhugg/benchmarks_tacas2015) that there are used functions like __VERIFIER_nondet_int() and __VERIFIER_assume(). However, trying this code reveals no error:

```C
#include <assert.h>
#include <pthread.h>

int x;

void __VERIFIER_assume(int);
int main(void)
{
        __VERIFIER_assume(x == 2); 
        assert(x == 1); 
        return 0;
}
```

Any clue?

Thanks,
M.

**Comment by carlleonardsson** [comment]
Hi,

The functions __VERIFIER_assume and __VERIFIER_nondet_* are documented in the manual of Nidhugg.

For __VERIFIER_assume(cnd), you can think of it as a function that checks the condition cnd, and blocks forever if the condition does not hold. This is sometimes useful for pruning the space of runs that you want the analysis to consider.

The code you suggest does not have an error (no assert violation). x is zero-initialized since it has static duration. So in the main function, x==2 will evaluate to false, the __VERIFIER_assume will block and control flow will never reach the assert statement. Nidhugg handles this case correctly.

If you instead were to declare x inside the main function, then x would not be initialized and x would be allowed to have any value. So in that case there would exist a run where the assert statement fails, because x just happened to have the value 2. Notice that this would be the case even if the __VERIFIER_assume function call was removed. However, Nidhugg does *not* handle such code correctly in general. This is because Nidhugg assumes that the given code does not have data-nondeterminism.

The __VERIFIER_nondet_* functions return unpredictable values. But they do not provide full support for data-nondeterminism. They are usually not all that useful because of this limitation. See the manual for details.

Best regards,
Carl Leonardsson

**Comment by mchalupa** [comment]
I see, thanks.

Marek
