### ISSUE TITLE
LLVM ERROR: Could not resolve external global address: _ZTIN5boost6detail16thread_data_baseE

### ISSUE THREAD

**Issue by ridhij93** [nidhugg/nidhugg#83]
Hi

I tried Nidhugg on an example with a call to libboost function. The code compiles fine with following flags: -lboost_system -lboost_date_time -lboost_thread -L /usr/local/lib/ -std=c++11 -fno-use-cxa-atexit. But when I run Nidhugg on the generated .ll file, I get the following error: 
LLVM ERROR: Could not resolve external global address: ZTIN5boost6detail16thread_data_baseE

I have tried Nidhugg on other examples as well that do not have any calls to external libraries and it runs fine. Is there something I am missing.

[I am using Clang-3.8]

**Comment by margnus1** [comment]
The issue here is that linking flags does not apply to the compile step (`clang -c`), which you are using to generate the .ll file. In order to test a program that uses external libraries, those libraries should be compiler to LLVM IR (usually the easiest way is using [wllvm](https://github.com/travitch/whole-program-llvm)), and then the IR should be linked to the program you wish to test using `llvm-link`.

The error message you get is from Nidhugg attempting to call the function as a black-box function, i.e. without interpreting it. This functionality is quite limited; in particular, the function may not have any other side-effects than reading and modifying memory. It may not even allocate memory! Thus, although it would be possible to load `libboost_thread.so` into the interpreter, doing so would surely crash nidhugg at runtime, or even worse, make the program behave differently than when run outside of nidhugg.

**Comment by margnus1** [comment]
I'm closing this issue for now, feel free to reopen it if you feel like your question has not been answered.
