### ISSUE TITLE
Testing under Debian stretch

### ISSUE THREAD

**Issue by kostis** [nidhugg/nidhugg#9]
On a machine that we recently upgraded to Debian stretch ('testing'), which has Boost 1.62, running the tests fails with:
```
./unittest --report_level=short --log_level=warning --run_test=""
Missing an argument value for the parameter run_test in the argument 

Parameter: run_test
 Filters, which test units to include or exclude from test module execution.
 Command line formats:
   --run_test=<test unit filter>
   -t <test unit filter>
 Environment variable: BOOST_TEST_RUN_FILTERS

For detailed help on Boost.Test parameters use:
  unittest --help
or
  unittest --help=<parameter name>
Makefile:1582: recipe for target 'test' failed
make[1]: *** [test] Error 200
```

If one goes ahead and runs the tests manually without the `-run_test=""` option, all tests except one pass:
```
cd src ; ./unittest --report_level=short --log_level=warning 
Running 534 test cases...
WARNING: Calling unknown external function memcpy as blackbox.
SC_test.cpp(2294): warning: in "SC_test/Atexit_multithreaded": Missing support for multithreaded atexit.

Test module "DPOR" has passed with:
  533 test cases out of 534 passed
  1 test case out of 534 passed with warnings
  994 assertions out of 994 passed
  1 failed warning
```
How does one fix this "Missing support for multithreaded atexit."?

PS. LLVM version is 3.8.1 if that makes any difference

**Comment by carlleonardsson** [comment]
Now testing should work via make test again.
$ make test

Additionally, you can run
$ make test UTEST='some filter'
to only run select tests.

The missing support for multithreaded atexit warning is because I have not implemented support for races between different calls to atexit from different threads. It is not currently a priority. If you find some real life code where it matters, let me know.

**Comment by kostis** [comment]
Thanks @carlleonardsson !
